### ISSUE TITLE
How can i check the final results after training the model?

### ISSUE THREAD

**Issue by Rabia-Noureen** [zhegan27/sentence_classification#2]
Hi it seems like a great work thanks for providing it. I am new to python and deep learning and I have trained my CNN classifier as instructed in the read me file now i have got 2 files eval_trec_cnn (Provides the test error and cost) and trec_cnn_result.npz (I dont know how to open it i think it contains the accuracy). Kindly help me out where can i find the final results (accuracy etc). 
Thanks in advance......

**Comment by Rabia-Noureen** [comment]
Sir kindly respond to my request asap because i am stuck with this problem.
Thanks

**Comment by zhegan27** [comment]
Sorry for the late response. 

As you said, after training the model, you will get two files: (1) eval_trec_cnn.log and (2) trec_cnn_result.npz. On the bottom of the log file, it says: final test err: 0.0724 std: 0.00763151361134. Therefore, if you only care about the accuracy, the accuracy is already there, i.e.,  1.0 - err = 92.76%. The second .npz file stores the learned parameters + test err. You need to read it as follows:

import numpy as np
from collections import OrderedDict

params = OrderedDict()
    
data = np.load('./trec_cnn_result.npz')  
for kk, pp in data.iteritems():
    params[kk] = data[kk]
    
acc = 1- params['test_err'] 

params also contains the learned params, for example, params['Wemb'] etc. 

Hope this helps you! 
Zhe

**Comment by Rabia-Noureen** [comment]
@zhegan27 Thanks for the detailed response, I have calculated the accuracy but for the other parameters i tried the script 

![image](https://user-images.githubusercontent.com/29410483/31163218-d52046a0-a8fa-11e7-9c69-dde55e259407.png)

But i got: 
IndentationError: expected an indented block  
Sorry if the error is too obvious to resolve but i am new to python.

Thanks in advance

**Comment by zhegan27** [comment]
That is because python has a strict requirement on indent. Below solves the problem. That is, you need to press the tab key on your keyboard to add some space before params[kk] = data[kk]. 

for kk, pp in data.iteritems():
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;params[kk] = data[kk]
